//! Autogenerated Unreal‑C++ code‑gen backend for SpacetimeDB CLI
use std::any::Any;
use std::ops::Deref;
use crate::Lang;
use std::fmt::{self, Write};
use spacetimedb_schema::def::{ModuleDef, TableDef, ReducerDef, TypeDef};
use crate::code_indenter::CodeIndenter;
use spacetimedb_schema::identifier::Identifier;
use spacetimedb_schema::schema::{Schema, TableSchema};
use crate::util::{print_auto_generated_file_comment, collect_case, fmt_fn, type_ref_name};
use convert_case::{Case, Casing};
use spacetimedb_schema::def::{IndexAlgorithm, BTreeAlgorithm};
use spacetimedb_primitives::ColId;
use crate::util::{iter_indexes};
use spacetimedb_schema::type_for_generate::{
    AlgebraicTypeDef, AlgebraicTypeUse, PlainEnumTypeDef, PrimitiveType, ProductTypeDef, SumTypeDef,
    TypespaceForGenerate,
};

pub struct UnrealCpp;

// ---------------------------------------------------------------------------
//  Lang impl
// ---------------------------------------------------------------------------

impl Lang for UnrealCpp {
    fn table_filename(&self, _module: &ModuleDef, table: &TableDef) -> String {
        format!("Tables/{}Table.g.h", table.name.deref().to_case(Case::Pascal))
    }
    fn type_filename(&self, type_name: &spacetimedb_schema::def::ScopedTypeName) -> String {
        format!("Types/{}.g.h", collect_case(Case::Pascal, type_name.name_segments()))
    }
    fn reducer_filename(&self, reducer_name: &Identifier) -> String {
        format!("Reducers/{}.g.h", reducer_name.deref().to_case(Case::Pascal))
    }

    fn generate_table(&self, module: &ModuleDef, table: &TableDef) -> String {
        
        let self_header = table.name.deref().to_case(Case::Pascal) + "Table";

        let mut output = UnrealCppAutogen::new(&[
            "SpacetimeRemoteTableHandle.g.h",
            // TODO: Client includes
            ], &self_header
        );

        let row_struct = format!("F{}", table.name.deref().to_case(Case::Pascal));   // e.g. "FMessage"
        let handle_cls = format!("U{}Table",  table.name.deref().to_case(Case::Pascal)); // "UMessageTable"

        let schema = TableSchema::from_module_def(module, table, (), 0.into())
            .validated()
            .expect("table schema should validate");


        writeln!(output, "UCLASS(BlueprintType)");
        writeln!(output, "class {} : public USpacetimeRemoteTableHandleBase", handle_cls);
        writeln!(output, "{{");
        writeln!(output, "    GENERATED_BODY()");
        writeln!(output);
        writeln!(output, "protected:");
        writeln!(output,
            "    virtual FString GetRemoteTableName() const override;"
        );
        writeln!(output, "    using FRow = {};", row_struct); // TODO: Do we need this?
        writeln!(output);

        let product_type = module.typespace_for_generate()[table.product_type_ref]
            .as_product()
            .unwrap();

        let mut index_field_names = Vec::new();

        for idx in iter_indexes(table) {
            let Some(accessor_name) = idx.accessor_name.as_ref() else { continue; };

            if let IndexAlgorithm::BTree(BTreeAlgorithm { columns }) = &idx.algorithm {
                // helper to turn a ColId into (FieldName, CppType)
                let field_info = |col: ColId| {
                    let (f_name, f_ty) = &product_type.elements[col.idx()];
                    (
                        f_name.deref().to_case(Case::Pascal),       // "UserId"
                        cpp_ty_fmt(module, f_ty).to_string(),               // "int32", "FString", …
                    )
                };

                // --- key type -------------------------------------------------
                let (key_type, key_expr) = match columns.as_singleton() {
                    Some(col) => {
                        let (fname, fty) = field_info(col);
                        (fty, format!("Row.{}", fname))
                    }
                    None => {
                        let mut members = Vec::<String>::new();
                        let mut exprs   = Vec::<String>::new();
                        for col in columns.iter() {
                            let (fname, fty) = field_info(col);
                            members.push(format!("{} {}", fty, fname));
                            exprs  .push(format!("Row.{}", fname));
                        }
                        let key_ty  = format!("struct {{ {} }}", members.join("; "));
                        let key_get = format!("{{ return {{ {} }}; }}", exprs.join(", "));
                        (key_ty, key_get)
                    }
                };

                let mut idx_cls  = accessor_name.deref().to_case(Case::Pascal); // e.g. "UserId"
                let base         = if schema.is_unique(columns) {
                    idx_cls.push_str("UniqueIndex");
                    "FUniqueIndexBase"
                } else {
                    idx_cls.push_str("Index");
                    "FBTreeIndexBase"
                };

                writeln!(output, "    struct {} : public {}<{}>", idx_cls, base, key_type);
                writeln!(output, "    {{");
                writeln!(output, "        explicit {}({}* InTable) : {}(InTable) {{}}", idx_cls, handle_cls, base);
                writeln!(output, "        virtual {} GetKey(const FRow& Row) const override {}", key_type, key_expr);
                writeln!(output, "    }};");
                writeln!(output);

                // field inside the handle
                writeln!(output, "public:");
                writeln!(output, "    {} {}{{ this }};", idx_cls, idx_cls);   // default-construct
                writeln!(output);

                index_field_names.push(idx_cls);
            }
        }

        writeln!(output, "public:");
        writeln!(output, "    explicit {}(USpacetimeDBConnection* InConn) : URemoteTableHandle(InConn) {{}}", handle_cls);

        // primary-key helper – same semantics as C#
        if let Some(pk) = schema.pk() {
            let pk_field = pk.col_name.deref().to_case(Case::Pascal);
            writeln!(output);
            writeln!(
                output,
                "    virtual uint64 GetPrimaryKey(const FRow& Row) const override {{ return Row.{}; }}",
                pk_field
            );
        }
        writeln!(output, "}};");    // end UCLASS

        output.into_inner()
    }


    fn generate_type(&self, module:&ModuleDef, typ:&TypeDef)->String {
        let name = typ.name.name_segments().last().map(|id| id.deref()).unwrap_or("Unnamed");

        match &module.typespace_for_generate()[typ.ty] {
            AlgebraicTypeDef::PlainEnum(plain_enum) => autogen_cpp_enum(name, plain_enum),
            AlgebraicTypeDef::Product(product_type_def) => autogen_cpp_struct(module, name, product_type_def),
            AlgebraicTypeDef::Sum(sum_type_def) => autogen_cpp_sum(module, name, sum_type_def),
        }
    }

    fn generate_reducer(&self, module:&ModuleDef, reducer:&ReducerDef)->String {
        let reducer_snake = reducer.name.deref();
        let pascal = reducer_snake.to_case(Case::Pascal);
        let mut header = UnrealCppAutogen::new(&[], &pascal);
        let class_name = format!("USpacetime{}Reducers",pascal);
        let call_func = format!("CallReducer_{}", pascal);
        let invoke_func = format!("Invoke{}", pascal);

        // ---- delegate macro -------------------------------------------------
        let macro_name = delegate_macro_name(reducer.params_for_generate.elements.len());
        writeln!(header,
            "{macro_name}(\n    F{pascal}Event,\n    const FReducerEventContext&, Context{}\n);",
            {
                // build extra params for delegate
                let mut extras = String::new();
                for (param, ty) in &reducer.params_for_generate.elements {
                    use std::fmt::Write as _;
                    write!(extras, ",\n    const {}&, {}",
                          cpp_ty_fmt(module, ty),
                          param.deref().to_case(Case::Pascal));
                }
                extras
            }
        );
        writeln!(header);

        writeln!(header, "UCLASS()");
        writeln!(header, "class {} : public UObject", class_name);
        writeln!(header, "{{");
        writeln!(header, "    GENERATED_BODY()\n");
        writeln!(header, "public:");

        write!(header, "    UFUNCTION(BlueprintCallable, Category=\"SpacetimeDB\")\n    void {}(", call_func);
        let mut first=true;
        for (param, ty) in &reducer.params_for_generate.elements {
            if !first { write!(header, ", "); } first=false;
            write!(header, "{} {}", cpp_ty_fmt(module, ty), param.deref());
        }
        writeln!(header, ");");
        writeln!(header);
        writeln!(header,
            "    UPROPERTY(BlueprintAssignable, Category=\"SpacetimeDB\")\n    F{pascal}Event On{pascal};");
        writeln!(header);
        write!(header,
            "    bool {}(const FReducerEventContext& Ctx, const F{}& Args);\n",
            invoke_func, pascal);
        writeln!(header, "}};");
        header.into_inner()
    }

    fn generate_globals(&self, module:&ModuleDef)->Vec<(String,String)> {
        let mut files = vec![];

        let mut base_hdr = UnrealCppAutogen::new(&[], "SpacetimeRemoteTableHandle");
        writeln!(base_hdr, "UCLASS(Abstract)");
        writeln!(base_hdr, "class USpacetimeRemoteTableHandleBase : public UObject {{");
        writeln!(base_hdr, "    GENERATED_BODY()\npublic:");
        writeln!(base_hdr, "    virtual FString GetRemoteTableName() const PURE_VIRTUAL(USpacetimeRemoteTableHandleBase::GetRemoteTableName, return TEXT(\"\"));");
        writeln!(base_hdr, "}};");
        files.push(("SpacetimeRemoteTableHandle.g.h".into(), base_hdr.into_inner()));

        let mut hdr = UnrealCppAutogen::new(&[], "SpacetimeDBClientGlobals");
        writeln!(hdr, "// Auto‑generated SpacetimeDB client globals for Unreal Engine\n");
        writeln!(hdr, "class FSpacetimeDBClientGlobals {{");
        writeln!(hdr, "public:");
        writeln!(hdr, "    static FString AuthTokenPath;\n    static FString HostURL;\n    static FString DbName;\n}};");
        files.push(("SpacetimeDBClientGlobals.g.h".into(), hdr.into_inner()));

        let mut cpp = UnrealCppAutogen::new_cpp(&["SpacetimeDBClientGlobals.g.h"]);
        writeln!(cpp, "FString FSpacetimeDBClientGlobals::AuthTokenPath = \"\";");
        writeln!(cpp, "FString FSpacetimeDBClientGlobals::HostURL    = \"\";");
        writeln!(cpp, "FString FSpacetimeDBClientGlobals::DbName      = \"\";\n");

        let mut populate_fields = String::new();

        // populate .cpp files per reducer
        for reducer in module.reducers() {
            let snake = reducer.name.deref();
            let pascal = snake.to_case(Case::Pascal);
            let header_include = format!("Reducers/{}.g.h", pascal);
            let mut rc_cpp = UnrealCppAutogen::new_cpp(&[&header_include]);

            write!(rc_cpp, "void USpacetime{}Reducers::CallReducer_{}(", pascal, pascal);
            let mut first=true;
            for (variant_name, variant_ty) in &reducer.params_for_generate.elements {
                if !first { write!(rc_cpp, ", "); } first=false;
                write!(rc_cpp, "{} {}", cpp_ty_fmt(module, variant_ty), variant_name.deref());
            }
            writeln!(rc_cpp, ")");
            writeln!(
    rc_cpp,
    r#"{{
    if (!Conn) {{ UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null")); return; }}

    // TODO: Build payload struct defined in generated Reducer
    FReducer::F{pascal} Payload{{}};
    // TODO: populate fields
{populate_fields}

    Conn->InternalCallReducer(
        Payload,
        SetReducerFlags ? SetReducerFlags->{pascal}Flags : FCallReducerFlags{{}}
    );
}}"#,
        pascal           = pascal,
        populate_fields  = populate_fields
    );


            // ---- Invoke implementation ----
            writeln!(rc_cpp,
                "bool USpacetime{}Reducers::Invoke{}(const FReducerEventContext& Ctx, const F{}& Args)", pascal, pascal, pascal);
            writeln!(rc_cpp, "{{");
            writeln!(rc_cpp, "    if (!On{}.IsBound())", pascal);
            writeln!(rc_cpp, "    {{");
            writeln!(rc_cpp, "        if (Ctx.Event.IsFailed() && OnUnhandledReducerError.IsBound())");
            writeln!(rc_cpp, "            OnUnhandledReducerError.Broadcast(Ctx, Ctx.Event.GetError());");
            writeln!(rc_cpp, "        return false;\n    }}");

            // broadcast line – build param list
            write!(rc_cpp, "    On{}.Broadcast(Ctx", pascal);
            for (param, _) in &reducer.params_for_generate.elements {
                write!(rc_cpp, ", Args.{}", param.deref().to_case(Case::Pascal));
            }
            writeln!(rc_cpp, ");");
            writeln!(rc_cpp, "    return true;\n}}\n");

            files.push((format!("Reducers/{}.g.cpp", pascal), rc_cpp.into_inner()));
        }

        files.push(("SpacetimeDBClientGlobals.g.cpp".into(), cpp.into_inner()));

        for table in module.tables() {
            let snake  = table.name.deref();                 // "message"
            let pascal = snake.to_case(Case::Pascal);        // "Message"
            let handle = format!("U{}Table", pascal);      // "UMessageTable"

            // Create the implementation (cpp) file for this handle
            let header_include = format!("Tables/{}Table.g.h", pascal);
            let mut tbl_cpp = UnrealCppAutogen::new_cpp(&[&header_include]);

            writeln!(tbl_cpp, "FString {}::GetRemoteTableName() const {{", handle);
            writeln!(tbl_cpp, "    return TEXT(\"{}\");", snake);
            writeln!(tbl_cpp, "}}\n");

            writeln!(tbl_cpp, "const TArray<F{}>& {}::GetRows() const {{", pascal, handle);
            writeln!(tbl_cpp, "    return Rows;");
            writeln!(tbl_cpp, "}}\n");

            files.push((format!("Tables/{}Table.g.cpp", pascal), tbl_cpp.into_inner()));
        }

        files
    }
}

struct UnrealCppAutogen {
    output: CodeIndenter<String>,
}

impl Deref for UnrealCppAutogen {
    type Target = CodeIndenter<String>;
    fn deref(&self) -> &Self::Target { &self.output }
}
impl std::ops::DerefMut for UnrealCppAutogen {
    fn deref_mut(&mut self) -> &mut Self::Target { &mut self.output }
}

impl UnrealCppAutogen {
    fn new(extra_includes: &[&str], self_header: &str) -> Self {
        let mut output = CodeIndenter::new(String::new(), "    ");
        print_auto_generated_file_comment(&mut output);
        writeln!(output, "#pragma once");
        writeln!(output, "#include \"CoreMinimal.h\"");
        for include in extra_includes { writeln!(output, "#include \"{include}\""); }
        writeln!(output, "#include \"{self_header}.g.generated.h\""); // need to include the generated header for Unreal's reflection
        writeln!(output);
        Self { output }
    }

    fn new_cpp(extra_includes: &[&str]) -> Self {
        let mut output = CodeIndenter::new(String::new(), "    ");
        print_auto_generated_file_comment(&mut output);
        for include in extra_includes { writeln!(output, "#include \"{include}\""); }
        writeln!(output);
        Self { output }
    }

    fn into_inner(self) -> String { self.output.into_inner() }
}

// ---------------------------------------------------------------------------
//  Helpers
// ---------------------------------------------------------------------------

// Choose the correct `DECLARE_DYNAMIC_MULTICAST_DELEGATE_*` macro based on
// how many **extra** parameters (besides `Context`) are required
fn delegate_macro_name(param_count: usize) -> &'static str {
    match param_count {
        0 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam",
        1 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams",
        2 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams",
        3 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams",
        4 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_FiveParams",
        _ => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_SixParams", // more can be added if needed
    }
}

fn autogen_cpp_struct(
    module: &ModuleDef,
    name: &str, // Changed to &str
    product_type: &ProductTypeDef,
) -> String {
     use std::collections::HashSet;
    let mut headers = HashSet::<String>::new();

    for (_, field_ty) in product_type {
        collect_includes_for_type(module, field_ty, &mut headers);
    }

    // Convert to `Vec<&str>` so UnrealCppAutogen::new works
    let mut slices: Vec<&str> = headers.iter().map(|s| s.as_str()).collect();
    slices.sort(); // make output deterministic

    // --------- start writing file ---------
    let mut output = UnrealCppAutogen::new(&slices, name);

    writeln!(output, "USTRUCT(BlueprintType)");
    writeln!(output, "struct F{}", name);
    writeln!(output, "{{");
    output.indent(1);
    writeln!(output, "GENERATED_BODY()");
    writeln!(output);

    for (orig_name, ty) in product_type.into_iter() {
        let field_name = orig_name.to_string();
        let ty_str = cpp_ty_fmt(module, ty).to_string();
        writeln!(output, "UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"SpacetimeDB\")");
        writeln!(output, "{} {};", ty_str, field_name);
        writeln!(output);
    }

    output.dedent(1);
    writeln!(output, "}};");

    output.into_inner()
}

// Helper function to generate a C++ enum definition
fn autogen_cpp_enum(name: &str, enum_type: &PlainEnumTypeDef) ->String { // Changed name to &str
    
    let mut output = UnrealCppAutogen::new(&[], name);
    writeln!(output, "UENUM(BlueprintType)");
    writeln!(output, "enum class E{} : uint8", name);
    writeln!(output, "{{");
    output.indent(1);

    for variant in &*enum_type.variants {
        writeln!(output, "{},", variant.deref().to_case(Case::Pascal)); // Ensure variants are PascalCase, common for UE enums
    }

    output.dedent(1);
    writeln!(output, "}};");
    
    output.into_inner()
}

// Unreal-C++ tagged-union (`enum` + payload struct)
fn autogen_cpp_sum(
    module: &ModuleDef,
    name: &str,              // e.g. "ClientMessage"
    sum_type: &SumTypeDef,
) -> String {
    // Gather header includes for each variant payload
    let mut includes = std::collections::HashSet::new();
    for (_, alg_ty) in &sum_type.variants {
        collect_includes_for_type(module, alg_ty, &mut includes);
    }
    let include_slices: Vec<&str> = includes.iter().map(|s| s.as_str()).collect();

    let mut output = UnrealCppAutogen::new(&include_slices, name);

    writeln!(output, "UENUM(BlueprintType)");
    writeln!(output, "enum class E{}Variant : uint8", name);
    writeln!(output, "{{");
    output.indent(1);
    for (variant_ident, _) in &sum_type.variants {
        writeln!(output, "{},", variant_ident.deref().to_case(Case::Pascal));
    }
    output.dedent(1);
    writeln!(output, "}};");
    writeln!(output);

    writeln!(output, "USTRUCT(BlueprintType)");
    writeln!(output, "struct F{}", name);
    writeln!(output, "{{");
    output.indent(1);

    writeln!(output, "GENERATED_BODY();");
    writeln!(output);

    // Tag field
    writeln!(
        output,
        "UPROPERTY(EditAnywhere, BlueprintReadWrite, Category=\"SpacetimeDB\")"
    );
    writeln!(output, "E{}Variant Variant;", name);
    writeln!(output);

    for (variant_name, variant_ty) in sum_type.variants.iter() {
        let variant_field_name = format!("As{}", variant_name.deref().to_case(Case::Pascal));
        let variant_ty_str = cpp_ty_fmt(module, variant_ty).to_string(); // One payload field *per* variant – note the `F` prefix

        writeln!(output, "UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"SpacetimeDB\")");

        // TODO: We can't use the TOptional with the blueprints. Need to look into it more
        // // ─── Only wrap in TOptional if the payload is *not* a plain BP value ──
        // if is_blueprint_plain_value(variant_ty) {
        //     // plain value → just the type itself
            writeln!(output, "{} {};", variant_ty_str, variant_field_name);
        // } else {
        //     // complex struct / enum etc. → optional wrapper
        //     writeln!(output, "TOptional<{}> {};", variant_ty_str, variant_field_name);
        // }
        writeln!(output);
    }

    output.dedent(1);
    writeln!(output, "}};");    // end USTRUCT

    output.into_inner()
}


fn cpp_ty_fmt<'a>(
    module: &'a ModuleDef,
    ty: &'a AlgebraicTypeUse,
) -> impl fmt::Display + 'a {
    fmt_fn(move |f| match ty {
        // --------- primitives etc ---------
        AlgebraicTypeUse::Primitive(p) => f.write_str(match p {
            PrimitiveType::Bool => "bool",
            PrimitiveType::I8   => "int8",
            PrimitiveType::U8   => "uint8",
            PrimitiveType::I16  => "int16",
            PrimitiveType::U16  => "int32", // uint16 is not supported by Unreal blueprints
            PrimitiveType::I32  => "int32",
            PrimitiveType::U32  => "int64", // uint32 is not supported by Unreal blueprints
            PrimitiveType::I64  => "int64",
            PrimitiveType::U64  => "int64", // TODO: uint64 is not supported by Unreal blueprints. Need to look a way so that we don't lose info here
            PrimitiveType::F32  => "float",
            PrimitiveType::F64  => "double",
            // TODO: assumed
            PrimitiveType::I128 => "FSpacetimeDBInt128",
            PrimitiveType::U128 => "FSpacetimeDBUInt128",
            PrimitiveType::I256 => "FSpacetimeDBInt256",
            PrimitiveType::U256 => "FSpacetimeDBUInt256",
        }),

        // byte-blob ⇒ TArray<uint8>
        AlgebraicTypeUse::Array(elem)
            if matches!(elem.as_ref(), AlgebraicTypeUse::Primitive(PrimitiveType::U8)) =>
                f.write_str("TArray<uint8>"),

        AlgebraicTypeUse::Array(elem) =>
            write!(f, "TArray<{}>", cpp_ty_fmt(module, elem)),

        AlgebraicTypeUse::String         => f.write_str("FString"),
        AlgebraicTypeUse::Identity       => f.write_str("FSpacetimeDBIdentity"),
        AlgebraicTypeUse::ConnectionId   => f.write_str("FSpacetimeDBConnectionId"),
        AlgebraicTypeUse::Timestamp      => f.write_str("FSpacetimeDBTimestamp"),
        AlgebraicTypeUse::TimeDuration   => f.write_str("FSpacetimeDBTimeDuration"),
        AlgebraicTypeUse::ScheduleAt     => f.write_str("FSpacetimeDBScheduleAt"),
        AlgebraicTypeUse::Unit           => f.write_str("FSpacetimeDBUnit"),

        // --------- references to user-defined types ---------
        AlgebraicTypeUse::Ref(r) => {
            let scoped = type_ref_name(module, *r);               // PascalCase
            match &module.typespace_for_generate()[*r] {
                AlgebraicTypeDef::PlainEnum(_) =>
                    write!(f, "E{}", scoped),                     // enum → EFoo
                AlgebraicTypeDef::Product(_) |
                AlgebraicTypeDef::Sum(_)       =>
                    write!(f, "F{}", scoped),                     // struct/record → FFoo
            }
        }

        // Options are *not* wrapped here; we decide optionality at call-site
        AlgebraicTypeUse::Option(inner) =>
            write!(f, "{}", cpp_ty_fmt(module, inner)),

        AlgebraicTypeUse::Never => unreachable!("never type"),
    })
}


// Given an `AlgebraicTypeUse`, add every referenced type’s generated
// header name (`"<FTypeName>.g.h"`) into `out` (a `HashSet` avoids dups).
fn collect_includes_for_type(
    module: &ModuleDef,
    ty: &AlgebraicTypeUse,
    out: &mut std::collections::HashSet<String>,
) {
    use AlgebraicTypeUse::*;
    match ty {
        Ref(r) => {
            let header = format!("{}.g.h", type_ref_name(module, *r));
            out.insert(header);
        }
        Option(inner) | Array(inner) => {
            collect_includes_for_type(module, inner, out);
        }
        // primitive / builtin types need no headers
        Identity | ConnectionId | Timestamp | TimeDuration | ScheduleAt
        | Unit | String | Primitive(_) | Never => {}
    }
}


// TODO: Not gonna use it until we sort out the TOptional problem with the BPs
// // Helper that tells us whether Unreal’s reflection system can expose a
// // property of this *exact* C++ type without extra wrapping.
// // (Blueprints do not understand TOptional<int32>, etc.)
// fn is_blueprint_plain_value(ty: &AlgebraicTypeUse) -> bool {
//     matches!(
//         ty,
//         // built-ins that turn into int32 / int64 / float / bool / FString …
//         AlgebraicTypeUse::Primitive(_)
//         | AlgebraicTypeUse::String
//         // byte-blob or other arrays become TArray<Primitive>
//         | AlgebraicTypeUse::Array(_)
//     )
// }