//! Autogenerated Unreal‑C++ code‑gen backend for SpacetimeDB CLI
use std::any::Any;
use std::ops::Deref;
use crate::Lang;
use std::fmt::{self, Write};
// use spacetimedb_lib::Identity;
use spacetimedb_schema::def::{ModuleDef, TableDef, ReducerDef, TypeDef};
use crate::code_indenter::CodeIndenter;
use spacetimedb_schema::identifier::Identifier;
use spacetimedb_schema::schema::{Schema, TableSchema};
use crate::util::{print_auto_generated_file_comment, collect_case, fmt_fn, type_ref_name};
use convert_case::{Case, Casing};
use spacetimedb_schema::def::{IndexAlgorithm, BTreeAlgorithm};
use spacetimedb_primitives::ColId;
use crate::util::{iter_indexes};
use spacetimedb_schema::type_for_generate::{
    AlgebraicTypeDef, AlgebraicTypeUse, PlainEnumTypeDef, PrimitiveType, ProductTypeDef, SumTypeDef,
    TypespaceForGenerate,
};

pub struct UnrealCpp;

const REDUCER_EVENTS: &str = r#"
// Context classes for event handling (equivalent to C# REDUCER_EVENTS)

USTRUCT(BlueprintType)
struct FEventContext
{
    GENERATED_BODY()

    FEventContext() = default;
    FEventContext(UDbConnection* InConn, const FEvent& InEvent);

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FEvent Event;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteTables* Db;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteReducers* Reducers;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSetReducerFlags SetReducerFlags;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    bool IsActive() const;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void Disconnect();

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionBuilder* SubscriptionBuilder();

private:
    UPROPERTY()
    UDbConnection* Conn;
};

USTRUCT(BlueprintType)
struct FReducerEventContext
{
    GENERATED_BODY()

    FReducerEventContext() = default;
    FReducerEventContext(UDbConnection* InConn, const FReducerEvent& InEvent);

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FReducerEvent Event;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteTables* Db;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteReducers* Reducers;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSetReducerFlags SetReducerFlags;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    bool IsActive() const;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void Disconnect();

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionBuilder* SubscriptionBuilder();

private:
    UPROPERTY()
    UDbConnection* Conn;
};

USTRUCT(BlueprintType)
struct FErrorContext
{
    GENERATED_BODY()

    FErrorContext() = default;
    FErrorContext(UDbConnection* InConn, const FString& InError);

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FString Error;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteTables* Db;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteReducers* Reducers;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSetReducerFlags SetReducerFlags;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    bool IsActive() const;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void Disconnect();

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionBuilder* SubscriptionBuilder();

private:
    UPROPERTY()
    UDbConnection* Conn;
};

USTRUCT(BlueprintType)
struct FSubscriptionEventContext
{
    GENERATED_BODY()

    FSubscriptionEventContext() = default;
    FSubscriptionEventContext(UDbConnection* InConn);

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteTables* Db;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    URemoteReducers* Reducers;

    UPROPERTY(BlueprintReadOnly, Category="SpacetimeDB")
    FSetReducerFlags SetReducerFlags;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    bool IsActive() const;

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    void Disconnect();

    UFUNCTION(BlueprintCallable, Category="SpacetimeDB")
    USubscriptionBuilder* SubscriptionBuilder();

private:
    UPROPERTY()
    UDbConnection* Conn;
};
"#;

// ---------------------------------------------------------------------------
//  Lang impl
// ---------------------------------------------------------------------------

impl Lang for UnrealCpp {
    fn table_filename(&self, _module: &ModuleDef, table: &TableDef) -> String {
        format!("Tables/{}Table.g.h", table.name.deref().to_case(Case::Pascal))
    }
    fn type_filename(&self, type_name: &spacetimedb_schema::def::ScopedTypeName) -> String {
        format!("Types/{}Type.g.h", collect_case(Case::Pascal, type_name.name_segments()))
    }
    fn reducer_filename(&self, reducer_name: &Identifier) -> String {
        format!("Reducers/{}.g.h", reducer_name.deref().to_case(Case::Pascal))
    }

    fn generate_table(&self, module: &ModuleDef, table: &TableDef) -> String {
        
        let self_header = table.name.deref().to_case(Case::Pascal) + "Table";

        let mut output = UnrealCppAutogen::new(&[
            "SpacetimeRemoteTableHandle.g.h",
            &format!("Types/{}Type.g.h", table.name.deref().to_case(Case::Pascal)),
            ], &self_header
        );

        let row_struct = format!("F{}Type", table.name.deref().to_case(Case::Pascal));   // e.g. "FUserType", "FMessageType"
        let handle_cls = format!("U{}Table",  table.name.deref().to_case(Case::Pascal)); // "UMessageTable"
        let table_name = table.name.deref().to_string();
        let table_pascal = table.name.deref().to_case(Case::Pascal);

        let schema = TableSchema::from_module_def(module, table, (), 0.into())
            .validated()
            .expect("table schema should validate");

        // Generate unique index classes first
        let product_type = module.typespace_for_generate()[table.product_type_ref]
            .as_product()
            ;

        let mut unique_indexes = Vec::new();

        for idx in iter_indexes(table) {
            let Some(accessor_name) = idx.accessor_name.as_ref() else { continue; };

            if let IndexAlgorithm::BTree(BTreeAlgorithm { columns }) = &idx.algorithm {
                if schema.is_unique(columns) {
                    if let Some(col) = columns.as_singleton() {
                        let (f_name, f_ty) = &product_type.unwrap().elements[col.idx()];
                        let field_name = f_name.deref().to_case(Case::Pascal);
                        let field_type = cpp_ty_fmt(module, f_ty).to_string();
                        let index_name = accessor_name.deref().to_case(Case::Pascal);
                        let index_class_name = format!("U{}{}UniqueIndex", table_pascal, index_name);

                        writeln!(output, "UCLASS(Blueprintable)");
                        writeln!(output, "class {} : public UUniqueIndexBase", index_class_name);
                        writeln!(output, "{{");
                        writeln!(output, "    GENERATED_BODY()");
                        writeln!(output);
                        writeln!(output, "protected:");
                        writeln!(output, "    virtual {} GetKey(const {}& Row) const override {{ return Row.{}; }}", field_type, row_struct, field_name);
                        writeln!(output, "}};");
                        writeln!(output);

                        unique_indexes.push((index_name, index_class_name, field_type));
                    }
                }
            }
        }

        writeln!(output, "UCLASS(BlueprintType)");
        writeln!(output, "class {} : public URemoteTableHandle", handle_cls);
        writeln!(output, "{{");
        writeln!(output, "    GENERATED_BODY()");
        writeln!(output);
        writeln!(output, "public:");

        // Generate unique index properties
        for (index_name, index_class_name, _) in &unique_indexes {
            writeln!(output, "    UPROPERTY(BlueprintReadOnly)");
            writeln!(output, "    {}* {};", index_class_name, index_name);
            writeln!(output);
        }

        writeln!(output, "    virtual void PostInitialize(UDbConnection* Conn) override");
        writeln!(output, "    {{");
        writeln!(output, "        Super::PostInitialize(Conn);");
        for (index_name, index_class_name, _) in &unique_indexes {
            writeln!(output, "        {} = NewObject<{}>(this);", index_name, index_class_name);
        }
        writeln!(output, "    }}");
        writeln!(output);

        // Generate table events in public section
        writeln!(output, "    // Table Events");
        writeln!(output, "    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOn{}Insert, const {}&, NewRow);", table_pascal, row_struct);
        writeln!(output, "    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOn{}Update, const {}&, OldRow, const {}&, NewRow);", table_pascal, row_struct, row_struct);
        writeln!(output, "    DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FOn{}Delete, const {}&, DeletedRow);", table_pascal, row_struct);
        writeln!(output);

        writeln!(output, "    UPROPERTY(BlueprintAssignable, Category = \"SpacetimeDB Events\")");
        writeln!(output, "    FOn{}Insert OnInsert;", table_pascal);
        writeln!(output);

        writeln!(output, "    UPROPERTY(BlueprintAssignable, Category = \"SpacetimeDB Events\")");
        writeln!(output, "    FOn{}Update OnUpdate;", table_pascal);
        writeln!(output);

        writeln!(output, "    UPROPERTY(BlueprintAssignable, Category = \"SpacetimeDB Events\")");
        writeln!(output, "    FOn{}Delete OnDelete;", table_pascal);
        writeln!(output);

        writeln!(output, "protected:");
        writeln!(output, "    virtual FString GetRemoteTableName() const override {{ return TEXT(\"{}\"); }}", table_name);
        
        // Add GetPrimaryKey method if table has a primary key
        if let Some(pk) = schema.pk() {
            let pk_field_name = pk.col_name.deref().to_case(Case::Pascal);
            let pk_field_type = {
                let (_, f_ty) = &product_type.unwrap().elements[pk.col_pos.idx()];
                cpp_ty_fmt(module, f_ty).to_string()
            };
            writeln!(output);
            writeln!(output, "    virtual {} GetPrimaryKey(const {}& Row) const override {{ return Row.{}; }}", pk_field_type, row_struct, pk_field_name);
        }

        writeln!(output);
        writeln!(output, "private:");
        writeln!(output, "    const FString TableName = TEXT(\"{}\");", table_name);

        writeln!(output, "}};");    // end UCLASS

        output.into_inner()
    }


    fn generate_type(&self, module:&ModuleDef, typ:&TypeDef)->String {
        let name = typ.name.name_segments().last().map(|id| id.deref()).unwrap_or("Unnamed");

        match &module.typespace_for_generate()[typ.ty] {
            AlgebraicTypeDef::PlainEnum(plain_enum) => autogen_cpp_enum(name, plain_enum),
            AlgebraicTypeDef::Product(product_type_def) => autogen_cpp_struct(module, name, product_type_def),
            AlgebraicTypeDef::Sum(sum_type_def) => autogen_cpp_sum(module, name, sum_type_def),
        }
    }

    fn generate_reducer(&self, module:&ModuleDef, reducer:&ReducerDef)->String {
        let reducer_snake = reducer.name.deref();
        let pascal = reducer_snake.to_case(Case::Pascal);
        let mut header = UnrealCppAutogen::new(&[], &pascal);
        let class_name = format!("USpacetime{}Reducers",pascal);
        let call_func = format!("CallReducer_{}", pascal);
        let invoke_func = format!("Invoke{}", pascal);

        // ---- delegate macro -------------------------------------------------
        let macro_name = delegate_macro_name(reducer.params_for_generate.elements.len());
        writeln!(header,
            "{macro_name}(\n    F{pascal}Event,\n    const FReducerEventContext&, Context{}\n);",
            {
                // build extra params for delegate
                let mut extras = String::new();
                for (param, ty) in &reducer.params_for_generate.elements {
                    use std::fmt::Write as _;
                    write!(extras, ",\n    const {}&, {}",
                          cpp_ty_fmt(module, ty),
                          param.deref().to_case(Case::Pascal));
                }
                extras
            }
        );
        writeln!(header);

        writeln!(header, "UCLASS()");
        writeln!(header, "class {} : public UObject", class_name);
        writeln!(header, "{{");
        writeln!(header, "    GENERATED_BODY()\n");
        writeln!(header, "public:");

        write!(header, "    UFUNCTION(BlueprintCallable, Category=\"SpacetimeDB\")\n    void {}(", call_func);
        let mut first=true;
        for (param, ty) in &reducer.params_for_generate.elements {
            if !first { write!(header, ", "); } first=false;
            write!(header, "{} {}", cpp_ty_fmt(module, ty), param.deref().to_case(Case::Pascal));
        }
        writeln!(header, ");");
        writeln!(header);
        writeln!(header,
            "    UPROPERTY(BlueprintAssignable, Category=\"SpacetimeDB\")\n    F{pascal}Event On{pascal};");
        writeln!(header);
        write!(header,
            "    bool {}(const FReducerEventContext& Ctx, const F{}& Args);\n",
            invoke_func, pascal);
        writeln!(header, "}};");
        header.into_inner()
    }

    fn generate_globals(&self, module:&ModuleDef)->Vec<(String,String)> {
        let mut files = vec![];

        // Generate the main SpacetimeDBClient file (replica of C# structure)
        let mut client_h = UnrealCppAutogen::new(&["SpacetimeDBSdk.g.h"], "SpacetimeDBClient");
        
        // Forward declarations
        writeln!(client_h, "// Forward declarations");
        writeln!(client_h, "class UDbConnection;");
        writeln!(client_h, "class URemoteTables;");
        writeln!(client_h, "class URemoteReducers;");
        writeln!(client_h, "class USubscriptionBuilder;");
        writeln!(client_h, "class USubscriptionHandle;");
        writeln!(client_h);

        // Context structs (like C# EventContext, ReducerEventContext, etc.)
        generate_context_structs(&mut client_h);

        // SetReducerFlags struct
        writeln!(client_h, "USTRUCT(BlueprintType)");
        writeln!(client_h, "struct FSetReducerFlags");
        writeln!(client_h, "{{");
        writeln!(client_h, "    GENERATED_BODY()");
        writeln!(client_h, "}};");
        writeln!(client_h);

        // RemoteTables class (like C# RemoteTables)
        generate_remote_tables_class(&mut client_h, module);

        // RemoteReducers class (like C# RemoteReducers)
        generate_remote_reducers_class(&mut client_h, module);

        // SubscriptionBuilder class
        generate_subscription_builder_class(&mut client_h);

        // SubscriptionHandle class
        generate_subscription_handle_class(&mut client_h);

        // Main DbConnection class (like C# DbConnection)
        generate_db_connection_class(&mut client_h, module);

        // Abstract Reducer base class (like C# Reducer)
        generate_reducer_base_class(&mut client_h, module);

        files.push(("SpacetimeDBClient.g.h".into(), client_h.into_inner()));

        // Generate the implementation file
        let mut client_cpp = UnrealCppAutogen::new_cpp(&["SpacetimeDBClient.g.h"]);
        generate_client_implementation(&mut client_cpp, module);
        files.push(("SpacetimeDBClient.g.cpp".into(), client_cpp.into_inner()));

        // No additional individual files - everything goes in the main client file
        files
    }
}

// Helper functions for generating the consolidated SpacetimeDBClient file

fn generate_context_structs(output: &mut UnrealCppAutogen) {
    writeln!(output, "// Context structs (like C# EventContext, ReducerEventContext, etc.)");
    writeln!(output, "// Generated from REDUCER_EVENTS pattern");
    writeln!(output, "{}", REDUCER_EVENTS);
    writeln!(output);
}

fn generate_remote_tables_class(output: &mut UnrealCppAutogen, module: &ModuleDef) {
    writeln!(output, "// RemoteTables class (like C# RemoteTables)");
    writeln!(output, "UCLASS(BlueprintType)");
    writeln!(output, "class URemoteTables : public URemoteTablesBase");
    writeln!(output, "{{");
    writeln!(output, "    GENERATED_BODY()");
    writeln!(output);
    writeln!(output, "public:");
    writeln!(output, "    void Initialize(UDbConnection* InConn);");
    writeln!(output);
    
    // Generate table handle properties  
    for table in module.tables() {
        let table_pascal = table.name.deref().to_case(Case::Pascal);
        writeln!(output, "    UPROPERTY(BlueprintReadOnly, Category=\"SpacetimeDB\")");
        writeln!(output, "    class U{}Table* {};", table_pascal, table_pascal);
        writeln!(output);
    }
    
    writeln!(output, "}};");
    writeln!(output);
}

fn generate_remote_reducers_class(output: &mut UnrealCppAutogen, module: &ModuleDef) {
    writeln!(output, "// RemoteReducers class (like C# RemoteReducers)");
    writeln!(output, "UCLASS(BlueprintType)");
    writeln!(output, "class URemoteReducers : public URemoteReducersBase");
    writeln!(output, "{{");
    writeln!(output, "    GENERATED_BODY()");
    writeln!(output);
    writeln!(output, "public:");
    writeln!(output, "    explicit URemoteReducers(UDbConnection* InConn, const FSetReducerFlags& InFlags);");
    writeln!(output);
    
    // Generate reducer events and call methods (following C# pattern)
    for reducer in module.reducers() {
        let reducer_pascal = reducer.name.deref().to_case(Case::Pascal);
        
        // Generate delegate for reducer event (like C# SendMessageHandler)
        let param_count = reducer.params_for_generate.elements.len() + 1; // +1 for context
        let delegate_macro = match param_count {
            1 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam",
            2 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams", 
            3 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams",
            4 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams",
            5 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_FiveParams",
            _ => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_SixParams",
        };
        
        write!(output, "    {}(\n        F{}Handler,\n        const FReducerEventContext&, Context", delegate_macro, reducer_pascal);
        for (param_name, param_type) in &reducer.params_for_generate.elements {
            write!(output, ",\n        const {}&, {}", cpp_ty_fmt(module, param_type), param_name.deref().to_case(Case::Pascal));
        }
        writeln!(output, "\n    );");
        
        writeln!(output, "    UPROPERTY(BlueprintAssignable, Category=\"SpacetimeDB\")");
        writeln!(output, "    F{}Handler On{};", reducer_pascal, reducer_pascal);
        writeln!(output);
        
        // Generate call method (like C# public void SendMessage(string text))
        write!(output, "    UFUNCTION(BlueprintCallable, Category=\"SpacetimeDB\")\n    void {}(", reducer_pascal);
        let mut first = true;
        for (param_name, param_type) in &reducer.params_for_generate.elements {
            if !first { write!(output, ", "); }
            first = false;
            write!(output, "const {}& {}", cpp_ty_fmt(module, param_type), param_name.deref().to_case(Case::Pascal));
        }
        writeln!(output, ");");
        writeln!(output);
        
        // Generate invoke method (like C# public bool InvokeSendMessage)
        write!(output, "    bool Invoke{}(const FReducerEventContext& Context, const U{}Reducer* Args);", reducer_pascal, reducer_pascal);
        writeln!(output);
    }
    
    // Internal error handling (like C# InternalOnUnhandledReducerError)
    writeln!(output, "    // Internal error handling");
    writeln!(output, "    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FInternalOnUnhandledReducerError, const FReducerEventContext&, Context, const FString&, Error);");
    writeln!(output, "    FInternalOnUnhandledReducerError InternalOnUnhandledReducerError;");
    writeln!(output);
    
    writeln!(output, "private:");
    writeln!(output, "    UPROPERTY()");
    writeln!(output, "    class UDbConnection* Conn;");
    writeln!(output);
    writeln!(output, "    UPROPERTY()");
    writeln!(output, "    FSetReducerFlags SetCallReducerFlags;");
    writeln!(output, "}};");
    writeln!(output);
}

fn generate_subscription_builder_class(output: &mut UnrealCppAutogen) {
    writeln!(output, "// SubscriptionBuilder class");
    writeln!(output, "UCLASS(BlueprintType)");
    writeln!(output, "class USubscriptionBuilder : public UObject");
    writeln!(output, "{{");
    writeln!(output, "    GENERATED_BODY()");
    writeln!(output);
    writeln!(output, "public:");
    writeln!(output, "    UFUNCTION(BlueprintCallable, Category=\"SpacetimeDB\")");
    writeln!(output, "    USubscriptionBuilder* OnApplied(FScriptDelegate Callback);");
    writeln!(output);
    writeln!(output, "    UFUNCTION(BlueprintCallable, Category=\"SpacetimeDB\")");
    writeln!(output, "    USubscriptionBuilder* OnError(FScriptDelegate Callback);");
    writeln!(output);
    writeln!(output, "    UFUNCTION(BlueprintCallable, Category=\"SpacetimeDB\")");
    writeln!(output, "    USubscriptionHandle* Subscribe(const TArray<FString>& SQL);");
    writeln!(output);
    writeln!(output, "private:");
    writeln!(output, "    UPROPERTY()");
    writeln!(output, "    class UDbConnection* Conn;");
    writeln!(output, "}};");
    writeln!(output);
}

fn generate_subscription_handle_class(output: &mut UnrealCppAutogen) {
    writeln!(output, "// SubscriptionHandle class");
    writeln!(output, "UCLASS(BlueprintType)");
    writeln!(output, "class USubscriptionHandle : public USubscriptionHandleBase");
    writeln!(output, "{{");
    writeln!(output, "    GENERATED_BODY()");
    writeln!(output);
    writeln!(output, "public:");
    writeln!(output, "    explicit USubscriptionHandle(UDbConnection* InConn);");
    writeln!(output);
    writeln!(output, "private:");
    writeln!(output, "    UPROPERTY()");
    writeln!(output, "    class UDbConnection* Conn;");
    writeln!(output, "}};");
    writeln!(output);
}

fn generate_db_connection_class(output: &mut UnrealCppAutogen, module: &ModuleDef) {
    writeln!(output, "// Main DbConnection class (like C# DbConnection)");
    writeln!(output, "UCLASS(BlueprintType)");
    writeln!(output, "class UDbConnection : public UDbConnectionBase");
    writeln!(output, "{{");
    writeln!(output, "    GENERATED_BODY()");
    writeln!(output);
    writeln!(output, "public:");
    writeln!(output, "    UDbConnection();");
    writeln!(output);
    writeln!(output, "    UPROPERTY(BlueprintReadOnly, Category=\"SpacetimeDB\")");
    writeln!(output, "    URemoteTables* Db;");
    writeln!(output);
    writeln!(output, "    UPROPERTY(BlueprintReadOnly, Category=\"SpacetimeDB\")");
    writeln!(output, "    URemoteReducers* Reducers;");
    writeln!(output);
    writeln!(output, "    UPROPERTY(BlueprintReadOnly, Category=\"SpacetimeDB\")");
    writeln!(output, "    FSetReducerFlags SetReducerFlags;");
    writeln!(output);
    writeln!(output, "    UFUNCTION(BlueprintCallable, Category=\"SpacetimeDB\")");
    writeln!(output, "    USubscriptionBuilder* SubscriptionBuilder();");
    writeln!(output);
    writeln!(output, "    // Error handling (like C# OnUnhandledReducerError)");
    writeln!(output, "    DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams(FOnUnhandledReducerError, const FReducerEventContext&, Context, const FString&, Error);");
    writeln!(output, "    UPROPERTY(BlueprintAssignable, Category=\"SpacetimeDB\")");
    writeln!(output, "    FOnUnhandledReducerError OnUnhandledReducerError;");
    writeln!(output);
    writeln!(output, "protected:");
    writeln!(output, "    // Abstract method implementations for reducer dispatching");
    writeln!(output, "    virtual UReducer* ToReducer(const FTransactionUpdate& Update) override;");
    writeln!(output, "    virtual bool Dispatch(const FReducerEventContext& Context, UReducer* Reducer) override;");
    writeln!(output);
    writeln!(output, "    // Hook up error handling to reducers (like C# add => Reducers.InternalOnUnhandledReducerError += value)");
    writeln!(output, "    virtual void PostInitProperties() override;");
    writeln!(output);
    writeln!(output, "    UFUNCTION()");
    writeln!(output, "    void OnUnhandledReducerErrorHandler(const FReducerEventContext& Context, const FString& Error);");
    writeln!(output, "}};");
    writeln!(output);
}

fn generate_reducer_base_class(output: &mut UnrealCppAutogen, module: &ModuleDef) {
    writeln!(output, "// Abstract Reducer base class (like C# Reducer)");
    writeln!(output, "UCLASS(Abstract, BlueprintType)");
    writeln!(output, "class UReducer : public UObject");
    writeln!(output, "{{");
    writeln!(output, "    GENERATED_BODY()");
    writeln!(output);
    writeln!(output, "public:");
    writeln!(output, "    virtual ~UReducer() = default;");
    writeln!(output, "}};");
    writeln!(output);
    
    // Generate specific reducer classes
    for reducer in module.reducers() {
        let reducer_pascal = reducer.name.deref().to_case(Case::Pascal);
        
        writeln!(output, "// {} Reducer class", reducer_pascal);
        writeln!(output, "UCLASS(BlueprintType)");
        writeln!(output, "class U{}Reducer : public UReducer", reducer_pascal);
        writeln!(output, "{{");
        writeln!(output, "    GENERATED_BODY()");
        writeln!(output);
        writeln!(output, "public:");
        
        // Generate properties for each parameter
        for (param_name, param_type) in &reducer.params_for_generate.elements {
            let param_pascal = param_name.deref().to_case(Case::Pascal);
            writeln!(output, "    UPROPERTY(BlueprintReadOnly, Category=\"SpacetimeDB\")");
            writeln!(output, "    {} {};", cpp_ty_fmt(module, param_type), param_pascal);
        }
        
        writeln!(output, "}};");
        writeln!(output);
    }
}

fn generate_client_implementation(output: &mut UnrealCppAutogen, module: &ModuleDef) {
    // UDbConnection constructor
    writeln!(output, "UDbConnection::UDbConnection()");
    writeln!(output, "{{");
    writeln!(output, "    Db = NewObject<URemoteTables>(this);");
    writeln!(output, "    Db->Initialize(this);");
    writeln!(output, "    Reducers = NewObject<URemoteReducers>(this, SetReducerFlags);");
    writeln!(output, "}}");
    writeln!(output);
    
    // URemoteTables Initialize method
    writeln!(output, "void URemoteTables::Initialize(UDbConnection* InConn)");
    writeln!(output, "{{");
    for table in module.tables() {
        let table_pascal = table.name.deref().to_case(Case::Pascal);
        writeln!(output, "    AddTable({} = NewObject<U{}Table>(this));", table_pascal, table_pascal);
    }
    writeln!(output, "}}");
    writeln!(output);
    
    // URemoteReducers constructor
    writeln!(output, "URemoteReducers::URemoteReducers(UDbConnection* InConn, const FSetReducerFlags& InFlags)");
    writeln!(output, "    : Conn(InConn), SetCallReducerFlags(InFlags)");
    writeln!(output, "{{");
    writeln!(output, "}}");
    writeln!(output);
    
    // Reducer implementations
    for reducer in module.reducers() {
        let reducer_pascal = reducer.name.deref().to_case(Case::Pascal);
        let reducer_snake = reducer.name.deref();
        
        // Call method implementation
        write!(output, "void URemoteReducers::{}(", reducer_pascal);
        let mut first = true;
        for (param_name, param_type) in &reducer.params_for_generate.elements {
            if !first { write!(output, ", "); }
            first = false;
            write!(output, "const {}& {}", cpp_ty_fmt(module, param_type), param_name.deref().to_case(Case::Pascal));
        }
        writeln!(output, ")");
        writeln!(output, "{{");
        writeln!(output, "    if (!Conn)");
        writeln!(output, "    {{");
        writeln!(output, "        UE_LOG(LogTemp, Error, TEXT(\"SpacetimeDB connection is null\"));");
        writeln!(output, "        return;");
        writeln!(output, "    }}");
        writeln!(output);
        writeln!(output, "    // Create reducer args");
        writeln!(output, "    U{}Reducer* Args = NewObject<U{}Reducer>();", reducer_pascal, reducer_pascal);
        for (param_name, _) in &reducer.params_for_generate.elements {
            let param_pascal = param_name.deref().to_case(Case::Pascal);
            writeln!(output, "    Args->{} = {};", param_pascal, param_pascal);
        }
        writeln!(output);
        writeln!(output, "    // Call reducer through connection");
        writeln!(output, "    Conn->InternalCallReducer(TEXT(\"{}\"), Args, SetCallReducerFlags);", reducer_snake);
        writeln!(output, "}}");
        writeln!(output);
        
        // Invoke method implementation (following C# pattern with error handling)
        write!(output, "bool URemoteReducers::Invoke{}(const FReducerEventContext& Context, const U{}Reducer* Args)", reducer_pascal, reducer_pascal);
        writeln!(output);
        writeln!(output, "{{");
        writeln!(output, "    if (!On{}.IsBound())", reducer_pascal);
        writeln!(output, "    {{");
        writeln!(output, "        // Handle unhandled reducer error (like C# InternalOnUnhandledReducerError)");
        writeln!(output, "        if (InternalOnUnhandledReducerError.IsBound())");
        writeln!(output, "        {{");
        writeln!(output, "            // TODO: Check Context.Event.Status for Failed/OutOfEnergy cases");
        writeln!(output, "            // For now, just broadcast any error");
        writeln!(output, "            InternalOnUnhandledReducerError.Broadcast(Context, TEXT(\"No handler registered for {}\"));", reducer_pascal);
        writeln!(output, "        }}");
        writeln!(output, "        return false;");
        writeln!(output, "    }}");
        writeln!(output);
        write!(output, "    On{}.Broadcast(Context", reducer_pascal);
        for (param_name, _) in &reducer.params_for_generate.elements {
            let param_pascal = param_name.deref().to_case(Case::Pascal);
            write!(output, ", Args->{}", param_pascal);
        }
        writeln!(output, ");");
        writeln!(output, "    return true;");
        writeln!(output, "}}");
        writeln!(output);
    }
    
    // Hook up error handling (like C# add => Reducers.InternalOnUnhandledReducerError += value)
    writeln!(output, "void UDbConnection::PostInitProperties()");
    writeln!(output, "{{");
    writeln!(output, "    Super::PostInitProperties();");
    writeln!(output, "    ");
    writeln!(output, "    // Connect OnUnhandledReducerError to Reducers.InternalOnUnhandledReducerError");
    writeln!(output, "    if (Reducers)");
    writeln!(output, "    {{");
    writeln!(output, "        Reducers->InternalOnUnhandledReducerError.AddDynamic(this, &UDbConnection::OnUnhandledReducerErrorHandler);");
    writeln!(output, "    }}");
    writeln!(output, "}}");
    writeln!(output);
    
    // Error handler method  
    writeln!(output, "UFUNCTION()");
    writeln!(output, "void UDbConnection::OnUnhandledReducerErrorHandler(const FReducerEventContext& Context, const FString& Error)");
    writeln!(output, "{{");
    writeln!(output, "    if (OnUnhandledReducerError.IsBound())");
    writeln!(output, "    {{");
    writeln!(output, "        OnUnhandledReducerError.Broadcast(Context, Error);");
    writeln!(output, "    }}");
    writeln!(output, "}}");
    writeln!(output);
    
    // Dispatch method (like C# protected override bool Dispatch)
    writeln!(output, "bool UDbConnection::Dispatch(const FReducerEventContext& Context, UReducer* Reducer)");
    writeln!(output, "{{");
    writeln!(output, "    if (!Reducer)");
    writeln!(output, "    {{");
    writeln!(output, "        return false;");
    writeln!(output, "    }}");
    writeln!(output);
    writeln!(output, "    // Dispatch to appropriate Invoke method (like C# reducer switch)");
    for reducer in module.reducers() {
        let reducer_pascal = reducer.name.deref().to_case(Case::Pascal);
        writeln!(output, "    if (U{}Reducer* Args = Cast<U{}Reducer>(Reducer))", reducer_pascal, reducer_pascal);
        writeln!(output, "    {{");
        writeln!(output, "        return Reducers->Invoke{}(Context, Args);", reducer_pascal);
        writeln!(output, "    }}");
    }
    writeln!(output);
    writeln!(output, "    // Unknown reducer type");
    writeln!(output, "    UE_LOG(LogTemp, Error, TEXT(\"Unknown reducer type in Dispatch\"));");
    writeln!(output, "    return false;");
    writeln!(output, "}}");
    writeln!(output);
    
    // Other implementations
    writeln!(output, "USubscriptionBuilder* UDbConnection::SubscriptionBuilder()");
    writeln!(output, "{{");
    writeln!(output, "    return NewObject<USubscriptionBuilder>(this);");
    writeln!(output, "}}");
    writeln!(output);
}

struct UnrealCppAutogen {
    output: CodeIndenter<String>,
}

impl Deref for UnrealCppAutogen {
    type Target = CodeIndenter<String>;
    fn deref(&self) -> &Self::Target { &self.output }
}
impl std::ops::DerefMut for UnrealCppAutogen {
    fn deref_mut(&mut self) -> &mut Self::Target { &mut self.output }
}

impl UnrealCppAutogen {
    fn new(extra_includes: &[&str], self_header: &str) -> Self {
        let mut output = CodeIndenter::new(String::new(), "    ");
        print_auto_generated_file_comment(&mut output);
        writeln!(output, "#pragma once");
        writeln!(output, "#include \"CoreMinimal.h\"");
        for include in extra_includes { writeln!(output, "#include \"{include}\""); }
        writeln!(output, "#include \"{}.g.generated.h\"", self_header); // need to include the generated header for Unreal's reflection
        writeln!(output);
        Self { output }
    }

    fn new_cpp(extra_includes: &[&str]) -> Self {
        let mut output = CodeIndenter::new(String::new(), "    ");
        print_auto_generated_file_comment(&mut output);
        for include in extra_includes { writeln!(output, "#include \"{include}\""); }
        writeln!(output);
        Self { output }
    }

    fn into_inner(self) -> String { self.output.into_inner() }
}

// ---------------------------------------------------------------------------
//  Helpers
// ---------------------------------------------------------------------------

// Choose the correct `DECLARE_DYNAMIC_MULTICAST_DELEGATE_*` macro based on
// how many **extra** parameters (besides `Context`) are required
fn delegate_macro_name(param_count: usize) -> &'static str {
    match param_count {
        0 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam",
        1 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams",
        2 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams",
        3 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams",
        4 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_FiveParams",
        _ => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_SixParams", // more can be added if needed
    }
}

use std::collections::HashSet;

fn autogen_cpp_struct(
    module: &ModuleDef,
    name: &str, // Changed to &str
    product_type: &ProductTypeDef,
) -> String {
    let mut headers = HashSet::<String>::new();

    for (_, field_ty) in product_type {
        collect_includes_for_type(module, field_ty, &mut headers);
    }

    // Convert to `Vec<&str>` so UnrealCppAutogen::new works
    let mut slices: Vec<&str> = headers.iter().map(|s| s.as_str()).collect();
    slices.sort(); // make output deterministic

    // --------- start writing file ---------
    let type_name = format!("{}Type", name);
    let mut output = UnrealCppAutogen::new(&slices, &type_name);

    writeln!(output, "USTRUCT(BlueprintType)");
    writeln!(output, "struct F{}Type", name);
    writeln!(output, "{{");
    output.indent(1);
    writeln!(output, "GENERATED_BODY()");
    writeln!(output);

    for (orig_name, ty) in product_type.into_iter() {
        let field_name = orig_name.deref().to_case(Case::Pascal);
        let ty_str = cpp_ty_fmt(module, ty).to_string();
        writeln!(output, "UPROPERTY(EditAnywhere, BlueprintReadWrite, Category = \"SpacetimeDB\")");
        writeln!(output, "{} {};", ty_str, field_name);
        writeln!(output);
    }

    output.dedent(1);
    writeln!(output, "}};");

    output.into_inner()
}

// Helper function to generate a C++ enum definition
fn autogen_cpp_enum(name: &str, enum_type: &PlainEnumTypeDef) ->String { // Changed name to &str
    
    let type_name = format!("{}Type", name);
    let mut output = UnrealCppAutogen::new(&[], &type_name);
    writeln!(output, "UENUM(BlueprintType)");
    writeln!(output, "enum class E{}Type : uint8", name);
    writeln!(output, "{{");
    output.indent(1);

    for variant in &*enum_type.variants {
        writeln!(output, "{},", variant.deref().to_case(Case::Pascal)); // Ensure variants are PascalCase, common for UE enums
    }

    output.dedent(1);
    writeln!(output, "}};");
    
    output.into_inner()
}

/// Generate Unreal-C++ code for a Rust tagged enum (`sum_type`)
///
/// * `module` – module in which the enum was defined
/// * `name`   – Pascal-case enum name, e.g. `"ClientMessage"`
/// * `sum_type` – parsed `SumTypeDef` containing the variants
///
/// The function returns the fully-formed `.h` body (the caller decides
/// whether to emit a matching `.cpp`; for header-only output, this is
/// enough).
fn autogen_cpp_sum(
    module: &ModuleDef,
    name: &str,
    sum_type: &SumTypeDef,
) -> String {
    use convert_case::{Case};

    /* ------------------------------------------------------------------ */
    /* 1. gather #includes for every variant payload -------------------- */
    /* ------------------------------------------------------------------ */
    let mut includes = HashSet::<String>::new();
    for (_, alg_ty) in &sum_type.variants {
        collect_includes_for_type(module, alg_ty, &mut includes);
    }
   
    // hardcoded include for instanced structs
    includes.insert("StructUtils/InstancedStruct.h".to_string());
    
    let include_slices: Vec<&str> = includes.iter().map(|s| s.as_str()).collect();

    // /* ------------------------------------------------------------------ */
    // /* 2. emit boiler-plate + forward decls ----------------------------- */
    // /* ------------------------------------------------------------------ */
    let mut out = UnrealCppAutogen::new(&include_slices, name);

    /* ------------------------------------------------------------------ */
    /* 3. generate the tag enum ----------------------------------------- */
    /* ------------------------------------------------------------------ */
    writeln!(
        out,
        "UENUM(BlueprintType)\nenum class E{}Tag : uint8\n{{",
        name
    )
    ;
    for (ix, (variant, _)) in sum_type.variants.iter().enumerate() {
        let comma = if ix + 1 == sum_type.variants.len() { "" } else { "," };
        writeln!(out, "    {}{}", variant.to_case(Case::Pascal), comma);
    }
    writeln!(out, "}};\n");

    /* ------------------------------------------------------------------ */
    /* 4. generate the wrapper UCLASS ----------------------------------- */
    /* ------------------------------------------------------------------ */
    writeln!(
        out,
        "UCLASS(BlueprintType)\nclass U{} : public UObject\n{{",
        name
    )
    ;
    writeln!(out, "    GENERATED_BODY()\n");

    // default ctor
    writeln!(out, "public:\n    U{}() = default;\n", name);

    // data + tag
    writeln!(
        out,
        "    UPROPERTY(EditAnywhere, BlueprintReadWrite, meta=(BaseStruct=\"/Script/Engine.InstancedStruct\"))\n    FInstancedStruct MessageData;"
    )
    ;
    writeln!(
        out,
        "    UPROPERTY(BlueprintReadWrite)\n    E{}Tag Tag;\n",
        name
    )
    ;

    /* 4a. Static factories per variant -------------------------------- */
    for (variant_name, _) in &sum_type.variants {
        let pas = variant_name.to_case(Case::Pascal);
        let fstruct = format!("F{}Type", pas);

        writeln!(
            out,
            "    UFUNCTION(BlueprintCallable)\n    static U{}* {}(const {}& Value)\n    {{",
            name, pas, fstruct
        )
        ;
        writeln!(out, "        U{}* Obj = NewObject<U{}>();", name, name);
        writeln!(
            out,
            "        Obj->Tag = E{}Tag::{};",
            name, pas
        )
        ;
        writeln!(
            out,
            "        Obj->MessageData.InitializeAs<{}>(Value);\n        return Obj;\n    }}\n",
            fstruct
        )
        ;
    }

    /* 4b. Get/Is helpers ---------------------------------------------- */
    for (variant_name, _) in &sum_type.variants {
        let pas = variant_name.to_case(Case::Pascal);
        let fstruct = format!("F{}Type", pas);

        // Is*
        writeln!(
            out,
            "    UFUNCTION(BlueprintCallable, BlueprintPure)\n    bool Is{}() const {{ return Tag == E{}Tag::{}; }}",
            pas, name, pas
        )
        ;

        // GetAs*
        writeln!(
            out,
            "\n    UFUNCTION(BlueprintCallable, BlueprintPure)\n    {} GetAs{}(bool& bIsValid) const\n    {{",
            fstruct, pas
        )
        ;
        writeln!(
            out,
            "        if (Is{}()) {{ bIsValid = true; return *MessageData.GetPtr<{}>(); }}",
            pas, fstruct
        )
        ;
        writeln!(
            out,
            "        bIsValid = false; return {}{{}};\n    }}\n",
            fstruct
        )
        ;
    }

    writeln!(out, "}}; // class {}\n", name);

    out.into_inner()
}

// Helper trait for Identifier case conversion
trait IdentifierCasing {
    fn to_case(&self, case: Case) -> String;
}

impl IdentifierCasing for Identifier {
    fn to_case(&self, case: Case) -> String {
        self.deref().to_case(case)
    }
}

fn cpp_ty_fmt<'a>(
    module: &'a ModuleDef,
    ty: &'a AlgebraicTypeUse,
) -> impl fmt::Display + 'a {
    fmt_fn(move |f| match ty {
        // --------- primitives etc ---------
        AlgebraicTypeUse::Primitive(p) => f.write_str(match p {
            PrimitiveType::Bool => "bool",
            PrimitiveType::I8   => "int8",
            PrimitiveType::U8   => "uint8",
            PrimitiveType::I16  => "int16",
            PrimitiveType::U16  => "int32", // uint16 is not supported by Unreal blueprints
            PrimitiveType::I32  => "int32",
            PrimitiveType::U32  => "int64", // uint32 is not supported by Unreal blueprints
            PrimitiveType::I64  => "int64",
            PrimitiveType::U64  => "int64", // TODO: uint64 is not supported by Unreal blueprints. Need to look a way so that we don't lose info here
            PrimitiveType::F32  => "float",
            PrimitiveType::F64  => "double",
            // TODO: assumed
            PrimitiveType::I128 => "FSpacetimeDBInt128",
            PrimitiveType::U128 => "FSpacetimeDBUInt128",
            PrimitiveType::I256 => "FSpacetimeDBInt256",
            PrimitiveType::U256 => "FSpacetimeDBUInt256",
        }),

        // byte-blob ⇒ TArray<uint8>
        AlgebraicTypeUse::Array(elem)
            if matches!(elem.as_ref(), AlgebraicTypeUse::Primitive(PrimitiveType::U8)) =>
                f.write_str("TArray<uint8>"),

        AlgebraicTypeUse::Array(elem) =>
            write!(f, "TArray<{}>", cpp_ty_fmt(module, elem)),

        AlgebraicTypeUse::String         => f.write_str("FString"),
        AlgebraicTypeUse::Identity       => f.write_str("FSpacetimeDBIdentity"),
        AlgebraicTypeUse::ConnectionId   => f.write_str("FSpacetimeDBConnectionId"),
        AlgebraicTypeUse::Timestamp      => f.write_str("FSpacetimeDBTimestamp"),
        AlgebraicTypeUse::TimeDuration   => f.write_str("FSpacetimeDBTimeDuration"),
        AlgebraicTypeUse::ScheduleAt     => f.write_str("FSpacetimeDBScheduleAt"),
        AlgebraicTypeUse::Unit           => f.write_str("FSpacetimeDBUnit"),

        // --------- references to user-defined types ---------
        AlgebraicTypeUse::Ref(r) => {
            let scoped = type_ref_name(module, *r);               // PascalCase
            match &module.typespace_for_generate()[*r] {
                AlgebraicTypeDef::PlainEnum(_) =>
                    write!(f, "E{}Type", scoped),                 // enum → EFooType
                AlgebraicTypeDef::Product(_) =>
                    write!(f, "F{}Type", scoped),                 // struct/record → FFooType
                AlgebraicTypeDef::Sum(_) =>
                    write!(f, "U{}", scoped),                     // sum type → UFoo (UClass)
            }
        }

        // Options are *not* wrapped here; we decide optionality at call-site
        AlgebraicTypeUse::Option(inner) =>
            write!(f, "{}", cpp_ty_fmt(module, inner)),

        AlgebraicTypeUse::Never => unreachable!("never type"),
    })
}


// Given an `AlgebraicTypeUse`, add every referenced type’s generated
// header name (`"<FTypeName>.g.h"`) into `out` (a `HashSet` avoids dups).
fn collect_includes_for_type(
    module: &ModuleDef,
    ty: &AlgebraicTypeUse,
    out: &mut std::collections::HashSet<String>,
) {
    use AlgebraicTypeUse::*;
    match ty {
        Ref(r) => {
            let header = format!("Types/{}Type.g.h", type_ref_name(module, *r));
            out.insert(header);
        }
        Option(inner) | Array(inner) => {
            collect_includes_for_type(module, inner, out);
        }
        // primitive / builtin types need no headers
        Identity | ConnectionId | Timestamp | TimeDuration | ScheduleAt
        | Unit | String | Primitive(_) | Never => {}
    }
}


// TODO: Not gonna use it until we sort out the TOptional problem with the BPs
// // Helper that tells us whether Unreal’s reflection system can expose a
// // property of this *exact* C++ type without extra wrapping.
// // (Blueprints do not understand TOptional<int32>, etc.)
// fn is_blueprint_plain_value(ty: &AlgebraicTypeUse) -> bool {
//     matches!(
//         ty,
//         // built-ins that turn into int32 / int64 / float / bool / FString …
//         AlgebraicTypeUse::Primitive(_)
//         | AlgebraicTypeUse::String
//         // byte-blob or other arrays become TArray<Primitive>
//         | AlgebraicTypeUse::Array(_)
//     )
// }