//! Autogenerated Unreal‑C++ code‑gen backend for SpacetimeDB CLI
use std::ops::Deref;
use crate::Lang;
use std::fmt::{self, Write};
use spacetimedb_schema::def::{ModuleDef, TableDef, ReducerDef, TypeDef};
use crate::code_indenter::CodeIndenter;
use spacetimedb_schema::identifier::Identifier;
use spacetimedb_schema::schema::{Schema, TableSchema};
use crate::util::{print_auto_generated_file_comment, collect_case, fmt_fn, type_ref_name};
use convert_case::{Case, Casing};
use spacetimedb_schema::def::{IndexAlgorithm, BTreeAlgorithm};
use spacetimedb_primitives::ColId;
use crate::util::{iter_indexes};
use spacetimedb_schema::type_for_generate::{
    AlgebraicTypeDef, AlgebraicTypeUse, PlainEnumTypeDef, PrimitiveType, ProductTypeDef, SumTypeDef,
    TypespaceForGenerate,
};

pub struct UnrealCpp;

// ---------------------------------------------------------------------------
//  Lang impl
// ---------------------------------------------------------------------------

impl Lang for UnrealCpp {
    fn table_filename(&self, _module: &ModuleDef, table: &TableDef) -> String {
        format!("Tables/{}Table.g.h", table.name.deref().to_case(Case::Pascal))
    }
    fn type_filename(&self, type_name: &spacetimedb_schema::def::ScopedTypeName) -> String {
        format!("Types/{}.g.h", collect_case(Case::Pascal, type_name.name_segments()))
    }
    fn reducer_filename(&self, reducer_name: &Identifier) -> String {
        format!("Reducers/{}.g.h", reducer_name.deref().to_case(Case::Pascal))
    }

    fn generate_table(&self, module: &ModuleDef, table: &TableDef) -> String {
        
        let self_header = table.name.deref().to_case(Case::Pascal) + "Table";

        let mut output = UnrealCppAutogen::new(&[
            "SpacetimeRemoteTableHandle.g.h",
            // TODO: Client includes
            ], &self_header
        );

        let row_struct = format!("F{}", table.name.deref().to_case(Case::Pascal));   // e.g. "FMessage"
        let handle_cls = format!("U{}Table",  table.name.deref().to_case(Case::Pascal)); // "UMessageTable"

        let schema = TableSchema::from_module_def(module, table, (), 0.into())
            .validated()
            .expect("table schema should validate");


        writeln!(output, "UCLASS(BlueprintType)");
        writeln!(output, "class {} : public USpacetimeRemoteTableHandleBase", handle_cls);
        writeln!(output, "{{");
        writeln!(output, "    GENERATED_BODY()");
        writeln!(output);
        writeln!(output, "protected:");
        writeln!(output,
            "    virtual FString GetRemoteTableName() const override;"
        );
        writeln!(output, "    using FRow = {};", row_struct); // TODO: Do we need this?
        writeln!(output);

        let product_type = module.typespace_for_generate()[table.product_type_ref]
            .as_product()
            .unwrap();

        let mut index_field_names = Vec::new();

        for idx in iter_indexes(table) {
            let Some(accessor_name) = idx.accessor_name.as_ref() else { continue; };

            if let IndexAlgorithm::BTree(BTreeAlgorithm { columns }) = &idx.algorithm {
                // helper to turn a ColId into (FieldName, CppType)
                let field_info = |col: ColId| {
                    let (f_name, f_ty) = &product_type.elements[col.idx()];
                    (
                        f_name.deref().to_case(Case::Pascal),       // "UserId"
                        cpp_ty_fmt(module, f_ty).to_string(),               // "int32", "FString", …
                    )
                };

                // --- key type -------------------------------------------------
                let (key_type, key_expr) = match columns.as_singleton() {
                    Some(col) => {
                        let (fname, fty) = field_info(col);
                        (fty, format!("Row.{}", fname))
                    }
                    None => {
                        let mut members = Vec::<String>::new();
                        let mut exprs   = Vec::<String>::new();
                        for col in columns.iter() {
                            let (fname, fty) = field_info(col);
                            members.push(format!("{} {}", fty, fname));
                            exprs  .push(format!("Row.{}", fname));
                        }
                        let key_ty  = format!("struct {{ {} }}", members.join("; "));
                        let key_get = format!("{{ return {{ {} }}; }}", exprs.join(", "));
                        (key_ty, key_get)
                    }
                };

                let mut idx_cls  = accessor_name.deref().to_case(Case::Pascal); // e.g. "UserId"
                let base         = if schema.is_unique(columns) {
                    idx_cls.push_str("UniqueIndex");
                    "FUniqueIndexBase"
                } else {
                    idx_cls.push_str("Index");
                    "FBTreeIndexBase"
                };

                writeln!(output, "    struct {} : public {}<{}>", idx_cls, base, key_type);
                writeln!(output, "    {{");
                writeln!(output, "        explicit {}({}* InTable) : {}(InTable) {{}}", idx_cls, handle_cls, base);
                writeln!(output, "        virtual {} GetKey(const FRow& Row) const override {}", key_type, key_expr);
                writeln!(output, "    }};");
                writeln!(output);

                // field inside the handle
                writeln!(output, "public:");
                writeln!(output, "    {} {}{{ this }};", idx_cls, idx_cls);   // default-construct
                writeln!(output);

                index_field_names.push(idx_cls);
            }
        }

        writeln!(output, "public:");
        writeln!(output, "    explicit {}(USpacetimeDBConnection* InConn) : URemoteTableHandle(InConn) {{}}", handle_cls);

        // primary-key helper – same semantics as C#
        if let Some(pk) = schema.pk() {
            let pk_field = pk.col_name.deref().to_case(Case::Pascal);
            writeln!(output);
            writeln!(
                output,
                "    virtual uint64 GetPrimaryKey(const FRow& Row) const override {{ return Row.{}; }}",
                pk_field
            );
        }

        writeln!(output, "}};");    // end UCLASS

        output.into_inner()
    }


    fn generate_type(&self, m:&ModuleDef, typ:&TypeDef)->String {
        let name = typ
            .name
            .name_segments()
            .last()
            .map(|id| id.deref())
            .unwrap_or("Unnamed");

        match &m.typespace_for_generate()[typ.ty] {
            AlgebraicTypeDef::Product(prod) => autogen_unreal_tuple(m, name, prod),
            AlgebraicTypeDef::Sum(sum) => autogen_unreal_sum(m, name, sum),
            AlgebraicTypeDef::PlainEnum(en) => autogen_unreal_plain_enum(name, en),
        }
    }

    fn generate_reducer(&self, module:&ModuleDef, reducer:&ReducerDef)->String {
        let reducer_snake = reducer.name.deref();
        let pascal = reducer_snake.to_case(Case::Pascal);
        let mut header = UnrealCppAutogen::new(&[], &pascal);
        let class_name = format!("USpacetime{}Reducers",pascal);
        let call_func = format!("CallReducer_{}", pascal);
        let invoke_func = format!("Invoke{}", pascal);

        // ---- delegate macro -------------------------------------------------
        let macro_name = delegate_macro_name(reducer.params_for_generate.elements.len());
        writeln!(header,
            "{macro_name}(\n    F{pascal}Event,\n    const FReducerEventContext&, Context{}\n);",
            {
                // build extra params for delegate
                let mut extras = String::new();
                for (param, ty) in &reducer.params_for_generate.elements {
                    use std::fmt::Write as _;
                    write!(extras, ",\n    const {}&, {}",
                          cpp_ty_fmt(module, ty),
                          param.deref().to_case(Case::Pascal));
                }
                extras
            }
        );
        writeln!(header);

        writeln!(header, "UCLASS()");
        writeln!(header, "class {} : public UObject", class_name);
        writeln!(header, "{{");
        writeln!(header, "    GENERATED_BODY()\n");
        writeln!(header, "public:");

        write!(header, "    UFUNCTION(BlueprintCallable, Category=\"SpacetimeDB\")\n    void {}(", call_func);
        let mut first=true;
        for (param, ty) in &reducer.params_for_generate.elements {
            if !first { write!(header, ", "); } first=false;
            write!(header, "{} {}", cpp_ty_fmt(module, ty), param.deref());
        }
        writeln!(header, ");");
        writeln!(header);
        writeln!(header,
            "    UPROPERTY(BlueprintAssignable, Category=\"SpacetimeDB\")\n    F{pascal}Event On{pascal};");
        writeln!(header);
        write!(header,
            "    bool {}(const FReducerEventContext& Ctx, const F{}& Args);\n",
            invoke_func, pascal);
        writeln!(header, "}};");
        header.into_inner()
    }

    fn generate_globals(&self, module:&ModuleDef)->Vec<(String,String)> {
        let mut files = vec![];

        let mut base_hdr = UnrealCppAutogen::new(&[], "SpacetimeRemoteTableHandle");
        writeln!(base_hdr, "UCLASS(Abstract)");
        writeln!(base_hdr, "class USpacetimeRemoteTableHandleBase : public UObject {{");
        writeln!(base_hdr, "    GENERATED_BODY()\npublic:");
        writeln!(base_hdr, "    virtual FString GetRemoteTableName() const PURE_VIRTUAL(USpacetimeRemoteTableHandleBase::GetRemoteTableName, return TEXT(\"\"));");
        writeln!(base_hdr, "}};");
        files.push(("SpacetimeRemoteTableHandle.g.h".into(), base_hdr.into_inner()));

        let mut hdr = UnrealCppAutogen::new(&[], "SpacetimeDBClientGlobals");
        writeln!(hdr, "// Auto‑generated SpacetimeDB client globals for Unreal Engine\n");
        writeln!(hdr, "class FSpacetimeDBClientGlobals {{");
        writeln!(hdr, "public:");
        writeln!(hdr, "    static FString AuthTokenPath;\n    static FString HostURL;\n    static FString DbName;\n}};");
        files.push(("SpacetimeDBClientGlobals.g.h".into(), hdr.into_inner()));

        let mut cpp = UnrealCppAutogen::new_cpp(&["SpacetimeDBClientGlobals.g.h"]);
        writeln!(cpp, "FString FSpacetimeDBClientGlobals::AuthTokenPath = \"\";");
        writeln!(cpp, "FString FSpacetimeDBClientGlobals::HostURL    = \"\";");
        writeln!(cpp, "FString FSpacetimeDBClientGlobals::DbName      = \"\";\n");

        let mut populate_fields = String::new();

        // populate .cpp files per reducer
        for reducer in module.reducers() {
            let snake = reducer.name.deref();
            let pascal = snake.to_case(Case::Pascal);
            let header_include = format!("Reducers/{}.g.h", pascal);
            let mut rc_cpp = UnrealCppAutogen::new_cpp(&[&header_include]);

            write!(rc_cpp, "void USpacetime{}Reducers::CallReducer_{}(", pascal, pascal);
            let mut first=true;
            for (variant_name, variant_ty) in &reducer.params_for_generate.elements {
                if !first { write!(rc_cpp, ", "); } first=false;
                write!(rc_cpp, "{} {}", cpp_ty_fmt(module, variant_ty), variant_name.deref());
            }
            writeln!(rc_cpp, ")");
            writeln!(
    rc_cpp,
    r#"{{
    if (!Conn) {{ UE_LOG(LogTemp, Error, TEXT("SpacetimeDB connection is null")); return; }}

    // TODO: Build payload struct defined in generated Reducer
    FReducer::F{pascal} Payload{{}};
    // TODO: populate fields
{populate_fields}

    Conn->InternalCallReducer(
        Payload,
        SetReducerFlags ? SetReducerFlags->{pascal}Flags : FCallReducerFlags{{}}
    );
}}"#,
        pascal           = pascal,
        populate_fields  = populate_fields
    );


            // ---- Invoke implementation ----
            writeln!(rc_cpp,
                "bool USpacetime{}Reducers::Invoke{}(const FReducerEventContext& Ctx, const F{}& Args)", pascal, pascal, pascal);
            writeln!(rc_cpp, "{{");
            writeln!(rc_cpp, "    if (!On{}.IsBound())", pascal);
            writeln!(rc_cpp, "    {{");
            writeln!(rc_cpp, "        if (Ctx.Event.IsFailed() && OnUnhandledReducerError.IsBound())");
            writeln!(rc_cpp, "            OnUnhandledReducerError.Broadcast(Ctx, Ctx.Event.GetError());");
            writeln!(rc_cpp, "        return false;\n    }}");

            // broadcast line – build param list
            write!(rc_cpp, "    On{}.Broadcast(Ctx", pascal);
            for (param, _) in &reducer.params_for_generate.elements {
                write!(rc_cpp, ", Args.{}", param.deref().to_case(Case::Pascal));
            }
            writeln!(rc_cpp, ");");
            writeln!(rc_cpp, "    return true;\n}}\n");

            files.push((format!("Reducers/{}.g.cpp", pascal), rc_cpp.into_inner()));
        }

        files.push(("SpacetimeDBClientGlobals.g.cpp".into(), cpp.into_inner()));

        for table in module.tables() {
            let snake  = table.name.deref();                 // "message"
            let pascal = snake.to_case(Case::Pascal);        // "Message"
            let handle = format!("U{}Table", pascal);      // "UMessageTable"

            // Create the implementation (cpp) file for this handle
            let header_include = format!("Tables/{}Table.g.h", pascal);
            let mut tbl_cpp = UnrealCppAutogen::new_cpp(&[&header_include]);

            writeln!(tbl_cpp, "FString {}::GetRemoteTableName() const {{", handle);
            writeln!(tbl_cpp, "    return TEXT(\"{}\");", snake);
            writeln!(tbl_cpp, "}}\n");

            writeln!(tbl_cpp, "const TArray<F{}>& {}::GetRows() const {{", pascal, handle);
            writeln!(tbl_cpp, "    return Rows;");
            writeln!(tbl_cpp, "}}\n");

            files.push((format!("Tables/{}Table.g.cpp", pascal), tbl_cpp.into_inner()));
        }

        files
    }
}

struct UnrealCppAutogen {
    output: CodeIndenter<String>,
}

impl Deref for UnrealCppAutogen {
    type Target = CodeIndenter<String>;
    fn deref(&self) -> &Self::Target { &self.output }
}
impl std::ops::DerefMut for UnrealCppAutogen {
    fn deref_mut(&mut self) -> &mut Self::Target { &mut self.output }
}

impl UnrealCppAutogen {
    fn new(extra_includes: &[&str], self_header: &str) -> Self {
        let mut output = CodeIndenter::new(String::new(), "    ");
        print_auto_generated_file_comment(&mut output);
        writeln!(output, "#pragma once");
        writeln!(output, "#include \"CoreMinimal.h\"");
        for include in extra_includes { writeln!(output, "#include \"{include}\""); }
        writeln!(output, "#include \"{self_header}.g.generated.h\""); // need to include the generated header for Unreal's reflection
        writeln!(output);
        Self { output }
    }

    fn new_cpp(extra_includes: &[&str]) -> Self {
        let mut output = CodeIndenter::new(String::new(), "    ");
        print_auto_generated_file_comment(&mut output);
        for include in extra_includes { writeln!(output, "#include \"{include}\""); }
        writeln!(output);
        Self { output }
    }

    fn into_inner(self) -> String { self.output.into_inner() }
}

// ---------------------------------------------------------------------------
//  Helpers
// ---------------------------------------------------------------------------

/// Choose the correct `DECLARE_DYNAMIC_MULTICAST_DELEGATE_*` macro based on
/// how many **extra** parameters (besides `Context`) are required
fn delegate_macro_name(param_count: usize) -> &'static str {
    match param_count {
        0 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam",
        1 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_TwoParams",
        2 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_ThreeParams",
        3 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_FourParams",
        4 => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_FiveParams",
        _ => "DECLARE_DYNAMIC_MULTICAST_DELEGATE_SixParams", // more can be added if needed
    }
}

/// Very lightweight formatter from Spacetime types to UE types
/// TODO: need to cover the other types
// fn ty_fmtdsdf(ty:&AlgebraicTypeUse)->&'static str {
//     match ty {
//         AlgebraicTypeUse::String           => "FString",
//         AlgebraicTypeUse::Array(_)         => "TArray<FString>",
//         AlgebraicTypeUse::Identity         => "FString",
//         AlgebraicTypeUse::Timestamp        => "FDateTime",
//         AlgebraicTypeUse::Option(_)        => "FString",          // treat Option<T> as nullable FString for now
//         AlgebraicTypeUse::Primitive(p) => match p {
//             PrimitiveType::I32          => "int32",
//             PrimitiveType::U32          => "uint32",
//             PrimitiveType::Bool         => "bool",
//             _               => "FString",
//         },
//         _ => "FString",
//     }
// }

fn cpp_ty_fmt<'a>(module: &'a ModuleDef, ty: &'a AlgebraicTypeUse) -> impl fmt::Display + 'a {
    fmt_fn(move |f| match ty {
        AlgebraicTypeUse::Identity => f.write_str("FSpacetimeDBIdentity"), // Assuming a USTRUCT/struct for Identity
        AlgebraicTypeUse::ConnectionId => f.write_str("FSpacetimeDBConnectionId"), // Assuming a USTRUCT/struct for ConnectionId
        AlgebraicTypeUse::ScheduleAt => f.write_str("FSpacetimeDBScheduleAt"), // Assuming a USTRUCT/struct
        AlgebraicTypeUse::Timestamp => f.write_str("FSpacetimeDBTimestamp"), // Assuming a USTRUCT/struct
        AlgebraicTypeUse::TimeDuration => f.write_str("FSpacetimeDBTimeDuration"), // Assuming a USTRUCT/struct
        AlgebraicTypeUse::Unit => f.write_str("FSpacetimeDBUnit"), // Assuming a USTRUCT/struct for Unit (or void/TSuccess?)
        AlgebraicTypeUse::Option(inner_ty) => {
            // Options can be represented as pointers, TObjects, or special wrapper structs
            // For primitives, a Tizen<Type> or nullable equivalent might be needed.
            // For USTRUCTs/UCLASSes, pointers are common for optionality.
            // Let's use TOptional for primitives and TSharedPtr for complex types as a general approach.
             match &**inner_ty {
                AlgebraicTypeUse::Primitive(_) => write!(f, "TOptional<{}>", cpp_ty_fmt(module, inner_ty)),
                _ => write!(f, "TSharedPtr<{}>", cpp_ty_fmt(module, inner_ty)),
            }
        }
        AlgebraicTypeUse::Array(elem_ty) => write!(f, "TArray<{}>", cpp_ty_fmt(module, elem_ty)),
        AlgebraicTypeUse::String => f.write_str("FString"),
        AlgebraicTypeUse::Ref(r) => {
            // Reference to another defined type (USTRUCT or UCLASS)
            let type_name = type_ref_name(module, *r); // type_ref_name now returns &ScopedTypeName
            let cpp_type_name = type_name.to_case(Case::Pascal);
            // Decide if it's a USTRUCT or UCLASS based on the definition
            match &module.typespace_for_generate()[*r] {
                 AlgebraicTypeDef::Product(_) => write!(f, "F{}", cpp_type_name), // Assuming Product types become USTRUCTs
                 AlgebraicTypeDef::Sum(_) => write!(f, "F{}", cpp_type_name), // Assuming Sum types become USTRUCTs
                 AlgebraicTypeDef::PlainEnum(_) => write!(f, "E{}", cpp_type_name), // Assuming Plain Enums become UENUMs
            }
        }
        AlgebraicTypeUse::Primitive(prim) => f.write_str(match prim {
            PrimitiveType::Bool => "bool",
            PrimitiveType::I8 => "int8",
            PrimitiveType::U8 => "uint8",
            PrimitiveType::I16 => "int16",
            PrimitiveType::U16 => "uint16",
            PrimitiveType::I32 => "int32",
            PrimitiveType::U32 => "uint32",
            PrimitiveType::I64 => "int64",
            PrimitiveType::U64 => "uint64",
            PrimitiveType::F32 => "float",
            PrimitiveType::F64 => "double",

            // Unreal Engine does not have native 128/256 bit integer types.
            PrimitiveType::I128 => "FSpacetimeDBInt128",    //TODO: No equivalent in Unreal
            PrimitiveType::U128 => "FSpacetimeDBUInt128",   //TODO: No equivalent in Unreal   
            PrimitiveType::I256 => "FSpacetimeDBInt256",    //TODO: No equivalent in Unreal
            PrimitiveType::U256 => "FSpacetimeDBUInt256",   //TODO: No equivalent in Unreal   
        }),     
        AlgebraicTypeUse::Never => unimplemented!(),
    })
}

// ---------------------------------------------------------------------------
//  Type generation helpers
// ---------------------------------------------------------------------------

fn autogen_unreal_product_common(
    module: &ModuleDef,
    name: &str,
    product_type: &ProductTypeDef,
) -> String {
    let struct_name = format!("F{}", name);
    let mut output = UnrealCppAutogen::new(&[], name);

    writeln!(output, "USTRUCT(BlueprintType)");
    writeln!(output, "struct {}", struct_name);
    writeln!(output, "{{");
    writeln!(output, "    GENERATED_BODY()\n");

    for (field, ty) in product_type {
        writeln!(output, "    UPROPERTY(BlueprintReadWrite)");
        writeln!(output, "    {} {};", cpp_ty_fmt(module, ty), field.deref());
    }

    writeln!(output, "}};");
    output.into_inner()
}

fn autogen_unreal_tuple(
    module: &ModuleDef,
    name: &str,
    tuple: &ProductTypeDef,
) -> String {
    autogen_unreal_product_common(module, name, tuple)
}

fn autogen_unreal_sum(
    module: &ModuleDef,
    name: &str,
    sum_type: &SumTypeDef,
) -> String {
    let struct_name = format!("F{}", name);
    let mut output = UnrealCppAutogen::new(&[], name);

    writeln!(output, "USTRUCT(BlueprintType)");
    writeln!(output, "struct {}", struct_name);
    writeln!(output, "{{");
    writeln!(output, "    GENERATED_BODY()\n");
    writeln!(output, "    UPROPERTY() uint8 Tag = 0;");

    for (variant_name, variant_ty) in &sum_type.variants {
        writeln!(output, "    UPROPERTY()");
        writeln!(output, "    {} {};", cpp_ty_fmt(module, variant_ty), variant_name.deref().to_case(Case::Pascal));
    }

    writeln!(output, "}};");
    output.into_inner()
}

fn autogen_unreal_plain_enum(name: &str, enum_type: &PlainEnumTypeDef) -> String {
    let enum_name = format!("E{}", name);
    let mut output = UnrealCppAutogen::new(&[], name);

    writeln!(output, "UENUM(BlueprintType)");
    writeln!(output, "enum class {} : uint8", enum_name);
    writeln!(output, "{{");
    for variant in &*enum_type.variants {
        writeln!(output, "    {},", variant.deref().to_case(Case::Pascal));
    }
    writeln!(output, "}};");

    output.into_inner()
}